### ISSUE TITLE
Future Suggestions/To Do

### ISSUE THREAD

**Issue by sryu1** [peterclifton/HighAirTrader#4]
- [ ] ![](https://geps.dev/progress/20) Improve the [wiki page](https://wiki.flightgear.org/HighAirTrader)
- [ ] ![](https://geps.dev/progress/20) More specialised missions for specific aircraft (i.e. freighters, cargo military aircraft) by changing distance & pay
- [ ] ![](https://geps.dev/progress/5) Add leaderboard
- [x] ![](https://geps.dev/progress/100) Add configs - save and load configs after closing and opening flightgear
- [x] ![](https://geps.dev/progress/100) Disable support for UFO, Bluebird, etc.
- [x] ![](https://geps.dev/progress/100) Option to change currency (Cosmetic function)
- [x] ![](https://geps.dev/progress/100) Disable time speedup - disabled when holding a job.
- [x] ![](https://geps.dev/progress/100) Rework GUI
- [x] ![](https://geps.dev/progress/100) Check if crashed on landing before rewarding (Works on a select few aircraft)

**Comment by sryu1** [comment]
https://github.com/sryu1/HighAirTrader

**Comment by peterclifton** [comment]
Thanks @sryu1 - love the ideas!  What's your thoughts re how the Leaderboard would work? Would it be along lines that players can play under different 'save game names' (i.e. all in single player mode or are you thinking of something that is multiplayer against other actual people?)

**Comment by sryu1** [comment]
I was thinking an actual multiplayer leaderboard where names could be saved as callsigns and data can be logged in a server so that no one cheats (we'll have to find how to disable time speed ups while logging for the leaderboard, maybe there can be an option to log or not log online so that users can use the time changing function when not competing with others). And maybe leaderboards can reset every week or month.

**Comment by peterclifton** [comment]
A multiplayer leaderboard on a server with call signs as names sounds like an excellent idea. Regular resets also good - will keep things fresh for players. There could even be one off special 1 day competitions from time to time etc...

**Comment by sryu1** [comment]
Implementing this may be a really hard task but I think it'll be worth it!

**Comment by peterclifton** [comment]
I think so too.  Its good working with you Sryu!
By the way I've published a new release v0.3.0 to bring the latest release up to date with where we've got to.  Also created a development branch that we can use for working on some of the more challenging features.

**Comment by sryu1** [comment]
Hey @peterclifton, would it be possible if I can get the correct permissions to commit directly into this repo so that I won't have to keep doing PRs?

**Comment by peterclifton** [comment]
Hi @sryu1 - yes - I've sent a collaborator invite to you now!

I see that you've been working on a placeholder for the leaderboard :)
I've pushed some changes to the development branch which adds a short-haul / long-haul choice to the config menu and some rudimentary logic to generate long-haul jobs if the user has that option selected.

**Comment by sryu1** [comment]
There's a typo in one of the videos hahaha
![image](https://github.com/peterclifton/HighAirTrader/assets/95025816/2e9ad20d-275e-434c-912f-c56f24189ae8)

**Comment by peterclifton** [comment]
thanks @sryu1 - well spotted! I'll get that corrected

**Comment by sryu1** [comment]
I'll now close this issue as they started some little progress. We can open separate issues for more specific things.

**Comment by peterclifton** [comment]
thanks @sryu1 , that sounds like a sensible approach :+1:
